# Generated by Django 4.0.4 on 2022-04-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybrary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mybrary_app.library'),
        ),
        migrations.AlterField(
            model_name='book',
            name='wishList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mybrary_app.wishlist'),
        ),
    ]
