# Generated by Django 4.0.4 on 2022-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybrary_app', '0002_alter_book_library_alter_book_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='public',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='public',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ManyToManyField(blank=True, null=True, related_name='book', to='mybrary_app.library'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='wishList',
        ),
        migrations.AddField(
            model_name='book',
            name='wishList',
            field=models.ManyToManyField(blank=True, null=True, related_name='book', to='mybrary_app.wishlist'),
        ),
    ]
