# Generated by Django 4.0.4 on 2022-04-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybrary_app', '0004_alter_book_library_alter_book_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mybrary_app.user'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mybrary_app.library'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='wishList',
        ),
        migrations.AddField(
            model_name='book',
            name='wishList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mybrary_app.wishlist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='mybrary_app.user'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishList', to='mybrary_app.user'),
        ),
    ]
