# Generated by Django 4.0.4 on 2022-04-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybrary_app', '0005_book_owner_remove_book_library_book_library_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mybrary_app.user'),
        ),
    ]
