# Generated by Django 4.0.4 on 2022-05-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybrary_app', '0006_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='mybrary_app.user'),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='mybrary_app.user'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishList', to='mybrary_app.user'),
        ),
    ]
